language: c
sudo: required
services:
  - docker
env:
  global:
    - REPO=bcal

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      	
        #Add power support
- os: linux
      dist: trusty
      compiler: gcc
	  arch: ppc64le
- os: linux
      dist: trusty
      compiler: clang
	  arch: 
     - ppc64le
     - amd64
    
    - os: linux
      dist: trusty
      compiler: clang
      	
        #Add power support
- os: linux
      dist: trusty
      compiler: gcc
	  arch: ppc64le
- os: linux
      dist: trusty
      compiler: clang
	  arch: 
     - ppc64le
     - amd64

#    - os: linux
#      compiler: musl-gcc
#      addons:
#        apt:
#          packages: &musl_packages
#          - musl
#          - musl-dev
#          - musl-tools
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get update -qy;
        sudo apt-get install -qy python3 python3-pip;
        python -m pip install logilab-common --user;
        python -m pip install pytest --user;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
        brew upgrade python;
        pip3 install logilab-common;
        pip3 install pytest;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$CC" == "clang" ]]; then brew update; brew install llvm; export PATH="/usr/local/opt/llvm/bin:$PATH"; fi; fi

script:
  - make clean; make strip;
  - pytest ./test.py;
  - make clean;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$CC" == "clang" ]]; then clang-tidy **/*.h **/*.c -- -Iinc; fi; fi

before_deploy:
  - cd ..
  - rm -rf $REPO/.git
  - tar -czf $REPO-${TRAVIS_TAG}.tar.gz $REPO
  - cd $REPO
  - sudo apt-get update -qy
  - sudo apt-get install -qy python3 python3-pip
  - sudo python3 -m pip install --upgrade pip
  - sudo python3 -m pip install --upgrade packagecore setuptools
  - packagecore -o dist/ "${TRAVIS_TAG#v}"
  - mv ../$REPO-${TRAVIS_TAG}.tar.gz dist/

deploy:
  provider: releases
  api-key:
    secure: u83OMgj7hh+PWsBKE95FVB9eXionEu6W9drx6xWAhqJgqAlCtPFBb0MLimJCXBN0cStAfSHPGp4ovd+3oiimvzBoVH6Kx/ySWQ0vMU6L/1lNMVuE+Z/mxI98eQFR5fC/TMYWHD4+KyTs9CIN/DMZ+CZVbuAtr9neMmjx3fWfqSNQw7VUhP/IVQOFze0FJAdeqp0tPjXPnsA2eRLhmypR+1kHx2v7iy2NmC5Gk/qzpsuihW+U6Eg6e2SFBxEzLSylqJHC9/nPItqFSrhghUasK6ofJ72A5CaAZ5J0KWug1lJDrx6bNUmR4J1bBYR+vp2es73I7eKTBQ0FFWJrSvIJ62DowL2wxhr6xeyaILADykchxaawXNNxyapOr7feGLjPMb0Cxh5w9dfNXIWoRGSQGrERr+TDLgIXZENqYVjNklQg3HK9J5gD9EWn2qmm9NPZ1c3JUOCW/4kf7FLLlbSDUO3VGdQXVyYKpo5vgoZr7MG9zFb7aFWeDeQJRDd+c4TaSuqgt4l1Krn2Pfg9zjv2dDQHS3ZlumvwHJtebLpzOKfmNCmeKFIROCXVT6ml4QxTj3mjy6ddWlulL9mxF79z8bgGYQ9f/gplfQ0shEOnmoJnSsvmw7nPFBsNRSAfyDJQ2TaJ1wgMOu6IfN9yNIo93AaUFKGTKzYk0g/Skg2Avy8=
  file_glob: true
  file:
    - dist/*
  skip_cleanup: true
  on:
    condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$CC == gcc"
    tags: true
    repo: jarun/bcal
